### ISSUE TITLE
How to use files from webpack-dev-server?

### ISSUE THREAD

**Issue by adriaandotcom** [fullpipe/twig-webpack-extension#19]
It looks like this library needs a static `manifest.json`. I got it working with static files which is great for production. For development however you would want to use the `webpack-dev-server` files.

We use docker with nginx to server the files. Would there be a work-a-round to get this working?

**Comment by fullpipe** [comment]
I have to check, but extention should work fine with remote manifest.json. 
```
parameters:
    webpack.manifest: http://localhost:9000/build/manifest.json
    webpack.public_path_js: "http://localhost:9000/"
    webpack.public_path_css: "http://localhost:9000/"
```
